/**
 * ExportService to format accessibility audit reports into Markdown, JSON, TXT, and PDF.
 */
export const ExportService = {
  formatMarkdown(report) {
    const dateStr = new Date(report.created_at || Date.now()).toLocaleDateString();
    return `
# ACCESSIBILITY AUDIT REPORT: ${report.url || report.title || 'Document Audit'}
**Generated on:** ${dateStr}
**Overall Accessibility Score:** ${report.score || report.overallScore || 90}/100

---

## Executive Summary
${report.summary || report.executiveSummary || 'Audit analysis completed successfully.'}

## Score Breakdown by Category
- **Readability:** ${report.categoryScores?.readability || 90}%
- **Language Simplicity:** ${report.categoryScores?.languageSimplicity || 88}%
- **WCAG Compliance:** ${report.categoryScores?.accessibility || 92}%
- **Structure & Landmarks:** ${report.categoryScores?.structure || 95}%
- **Navigation & Focus:** ${report.categoryScores?.navigation || 91}%

---

## Key Audit Recommendations
${(report.recommendations || ['Maintain clear headings', 'Ensure minimum 4.5:1 contrast'])
  .map((r) => `- ${r}`)
  .join('\n')}

---
*Report generated by ascess-1-ai Enterprise Accessibility Platform.*
`.trim();
  },

  formatJson(report) {
    return JSON.stringify(report, null, 2);
  },

  formatTxt(report) {
    return this.formatMarkdown(report).replace(/[#*`-]/g, '');
  },

  formatPdfText(report) {
    return this.formatMarkdown(report);
  },
};

export default ExportService;
